// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqPPF_0ZbQhnMBVFCnOZHCSge_Jm9sqjQ',
    appId: '1:450567145174:web:cc5f7d34cd8f0f8ba8ab77',
    messagingSenderId: '450567145174',
    projectId: 'carded-firebase',
    authDomain: 'carded-firebase.firebaseapp.com',
    storageBucket: 'carded-firebase.appspot.com',
    measurementId: 'G-KRDCER6VRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALT20ewlEqteCVQwUkrx6fDJ-5q2P8R4U',
    appId: '1:450567145174:android:8f1976cbb56cbf66a8ab77',
    messagingSenderId: '450567145174',
    projectId: 'carded-firebase',
    storageBucket: 'carded-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2wXTbe9S3FrQi86G9jVgPbvWehmOKXJU',
    appId: '1:450567145174:ios:f1f497eee5a30af0a8ab77',
    messagingSenderId: '450567145174',
    projectId: 'carded-firebase',
    storageBucket: 'carded-firebase.appspot.com',
    iosClientId: '450567145174-t4fq1fvs03ideiprkmde77q0lqec8l8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.carded',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2wXTbe9S3FrQi86G9jVgPbvWehmOKXJU',
    appId: '1:450567145174:ios:f1f497eee5a30af0a8ab77',
    messagingSenderId: '450567145174',
    projectId: 'carded-firebase',
    storageBucket: 'carded-firebase.appspot.com',
    iosClientId: '450567145174-t4fq1fvs03ideiprkmde77q0lqec8l8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.carded',
  );
}
